version: "2"
services:
  gateway:
    build: nginx
    links:
      - book
      - auth
    ports:
      - "80:80"
    depends_on:
      - book
  book:
    image: driverpt/book-service
    ports:
      - "80"
    environment:
      - APP_PORT=80
  auth:
    image: driverpt/auth-service
    ports:
      - "80"
    environment:
      - APP_PORT=80










  #redis:
  #  image: redis:3.2-alpine
  #  ports:
  #    - "6379:6379"

