server:
  port: ${APP_PORT:8081}
  contextPath: /
security:
  jwt:
    signing:
      key: ${SECRET_KEY:changeit}
  user:
    name: bar
    password: foo
spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  resources:
    cachePeriod: 604800
  thymeleaf:
    cache: false
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
