server:
  port: 8000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG

spring:
  cloud:
    config:
      discovery:
        enabled: true
