server:
  port: ${APP_PORT:8080}
  contextPath: /

endpoints:
  health:
    sensitive: false
  restart:
    enabled: false
  shutdown:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  resources:
    cachePeriod: 604800
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: 6379
